# Use the official Node.js image as the base image
FROM node AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the Angular application
RUN npm run build --prod

# Use a smaller nginx image to serve the Angular app
FROM nginx:alpine

# Copy the built Angular app from the builder stage
COPY --from=builder /app/dist/image-classification-app /usr/share/nginx/html

# Expose the port that nginx will listen on
EXPOSE 80

# Start nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]
