# Stage 1: Build
FROM tensorflow/tensorflow:latest as build

WORKDIR /app


# Copy and install Python dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy application files
COPY . .

# Expose the FastAPI port
EXPOSE 80

# Command to run the FastAPI application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]